plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ankit.greedling'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ankit.greedling'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '0.1.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
