import * as THREE from './three.module.js';
import { ITEMS, MODS, UPGRADES } from './catalog.mjs';

const el = (id) => document.getElementById(id);
const hud = {
  root:el('hud'), gold:el('gold'), value:el('value'), stack:el('stack'), best:el('best'),
  dawn:el('dawnBar'), leanBar:el('leanBar'), time:el('time'), lean:el('lean'), toast:el('toast')
};
const screens={start:el('start'),level:el('levelup'),end:el('end'),den:el('den')};
const keys=new Set(), mods=new Set(), comboSeen=new Set();
const touch=new THREE.Vector2();
let running=false, paused=false, raidTime=0, raidGold=0, lean=0, maxSlots=6, nextLevel=0;
let packReady=0, ghostUntil=0, guardCooldown=0, catReady=0, slowUntil=0, rerolled=false, uid=1;
let target=null, audioCtx=null, toastTimer=0;
let bank=Number(localStorage.getItem('greedling.bank')||0), best=Number(localStorage.getItem('greedling.best')||0);
let meta=readJSON('greedling.meta',{owned:{},codex:[]}); if(!meta.owned)meta.owned={}; if(!meta.codex)meta.codex=[];
const codex=new Set(meta.codex);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const RAID=360, GRACE=20;

function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}
function save(){meta.codex=[...codex];localStorage.setItem('greedling.meta',JSON.stringify(meta));localStorage.setItem('greedling.bank',String(bank));localStorage.setItem('greedling.best',String(best));}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function rnd(a,b){return a+Math.random()*(b-a)} function one(a){return a[(Math.random()*a.length)|0]}
function tags(d,t){return d.tags.indexOf(t)>=0} function vibrate(x){if(navigator.vibrate)navigator.vibrate(x)}
function sound(f=440,d=.05,g=.025){if(!audioCtx)return;const o=audioCtx.createOscillator(),v=audioCtx.createGain();o.type='triangle';o.frequency.value=f;v.gain.value=g;o.connect(v);v.connect(audioCtx.destination);o.start();v.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.stop(audioCtx.currentTime+d)}
addEventListener('pointerdown',()=>{if(!audioCtx){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume()}catch{}}},{once:true});
function toast(s,bad=false){hud.toast.textContent=s;hud.toast.style.color=bad?'#ff9d79':'#f4d892';hud.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>hud.toast.classList.remove('show'),850)}

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x071014); scene.fog=new THREE.Fog(0x071014,18,55);
const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,100);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;el('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x7892a2,0x180f09,1.5));const keyLight=new THREE.DirectionalLight(0xffd39a,2.1);keyLight.position.set(8,15,6);keyLight.castShadow=true;keyLight.shadow.mapSize.set(1024,1024);scene.add(keyLight);
const ground=new THREE.Mesh(new THREE.CylinderGeometry(23,23,.5,64),new THREE.MeshStandardMaterial({color:0x151b1e,roughness:.9,metalness:.08}));ground.position.y=-.28;ground.receiveShadow=true;scene.add(ground);
const rim=new THREE.Mesh(new THREE.TorusGeometry(22.7,.1,6,72),new THREE.MeshBasicMaterial({color:0x6d5839}));rim.rotation.x=Math.PI/2;scene.add(rim);
const decor=new THREE.Group(),lootRoot=new THREE.Group(),guardRoot=new THREE.Group();scene.add(decor,lootRoot,guardRoot);
const player=new THREE.Group(),stackRoot=new THREE.Group();scene.add(player);player.add(stackRoot);stackRoot.position.set(0,1.55,.48);
const carried=[],loot=[],stalls=[],guards=[];let gate=null;
function material(c,e=0){return new THREE.MeshStandardMaterial({color:c,roughness:.62,metalness:.16,emissive:e,emissiveIntensity:e?1.1:0})}
function box(w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(c));m.castShadow=m.receiveShadow=true;return m}
function goblin(){const b=box(.72,.78,.5,0x426a3d);b.position.y=.75;player.add(b);const h=new THREE.Mesh(new THREE.SphereGeometry(.42,12,8),material(0x5f8a4c));h.position.y=1.37;h.castShadow=true;player.add(h);for(const s of[-1,1]){const ear=new THREE.Mesh(new THREE.ConeGeometry(.17,.58,3),material(0x5f8a4c));ear.position.set(s*.49,1.43,0);ear.rotation.z=-s*Math.PI/2;player.add(ear);const eye=new THREE.Mesh(new THREE.SphereGeometry(.055,8,6),new THREE.MeshBasicMaterial({color:0xffd85e}));eye.position.set(s*.15,1.45,-.36);player.add(eye)}const sack=box(.6,.6,.32,0x6d4a30);sack.position.set(0,.98,.38);player.add(sack)} goblin();
function makeMarket(){for(let i=0;i<8;i++){const a=i/8*Math.PI*2+.18,r=16.2,g=new THREE.Group();g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);g.rotation.y=-a+Math.PI/2;const c=box(2.45,.78,1.2,i===5?0x6d4f25:0x382f29);c.position.y=.4;g.add(c);const roof=box(2.9,.16,1.5,0x6a3c28);roof.position.y=2.12;g.add(roof);for(const x of[-1.15,1.15]){const p=box(.12,1.8,.12,0x755334);p.position.set(x,1.15,.45);g.add(p)}const l=new THREE.PointLight(0xffb45e,6,6,2);l.position.set(0,1.75,-.35);g.add(l);const ring=new THREE.Mesh(new THREE.RingGeometry(1.35,1.75,30),new THREE.MeshBasicMaterial({color:0xc4a46a,transparent:true,opacity:.24,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(0,.02,-1.65);g.add(ring);decor.add(g);stalls.push(new THREE.Vector3(Math.cos(a)*(r-1.65),0,Math.sin(a)*(r-1.65)))}const g=new THREE.Group();g.position.set(0,0,20.5);const l=box(.65,4,.65,0x655238),r=l.clone();l.position.set(-2,2,0);r.position.set(2,2,0);g.add(l,r);const top=box(4.7,.55,.65,0xc4a46a);top.position.y=4;g.add(top);const glow=new THREE.PointLight(0xffc15b,9,9,2);glow.position.set(0,3,0);g.add(glow);decor.add(g);gate=new THREE.Vector3(0,0,19.3)} makeMarket();
function makeGuard(radius,phase,speed){const g=new THREE.Group();const body=box(.55,1.25,.5,0x2b3440);body.position.y=.8;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.28,10,7),material(0xcab08b));head.position.y=1.62;g.add(head);const lamp=new THREE.PointLight(0xffc66a,5,5,2);lamp.position.set(0,1.55,-.45);g.add(lamp);guardRoot.add(g);guards.push({g,radius,phase,speed})}makeGuard(10,0,.26);makeGuard(13.2,2.1,-.21);makeGuard(17,4.4,.17);
function itemMesh(d){let geo;if(tags(d,'food')||tags(d,'critter'))geo=new THREE.SphereGeometry(.34,10,7);else if(d.id==='bell')geo=new THREE.ConeGeometry(.34,.55,12);else if(d.id==='crown')geo=new THREE.CylinderGeometry(.4,.3,.42,8);else if(d.id==='lantern')geo=new THREE.CylinderGeometry(.27,.3,.58,8);else geo=new THREE.BoxGeometry(.62,.42,.58);const m=new THREE.Mesh(geo,material(d.color,d.id==='gem'?0x124b4d:0));m.castShadow=m.receiveShadow=true;return m}
function spawn(d,x,z,expires=0){const m=itemMesh(d);m.position.set(x,.35,z);m.rotation.y=rnd(0,6.28);lootRoot.add(m);loot.push({d,m,expires})}
function resetLoot(){while(loot.length)lootRoot.remove(loot.pop().m);while(carried.length)stackRoot.remove(carried.pop().m)}
function fillBazaar(){resetLoot();[ITEMS[0],ITEMS[1],ITEMS[2]].forEach((d,i)=>spawn(d,-2+i*2,-4+i*.4));for(let i=0;i<40;i++){const a=rnd(0,6.28),r=rnd(4.5,20);spawn(one(ITEMS),Math.cos(a)*r,Math.sin(a)*r)}}
function value(){let n=0;for(let i=0;i<carried.length;i++){const e=carried[i];let v=e.d.value*e.mult;if(mods.has('food2x')&&tags(e.d,'food'))v*=2;if(mods.has('top2x')&&i===carried.length-1)v*=2;n+=v}if(carried.filter(e=>tags(e.d,'food')).length>=3)n*=1.18;return Math.round(n)}
function weight(){return carried.reduce((n,e)=>n+e.d.weight,0)}
function layout(){for(let i=0;i<carried.length;i++){const e=carried[i];e.m.position.set(Math.sin(i*1.7)*.07,i*.56,0);e.m.rotation.set(0,i*.2,0)}hud.stack.textContent=carried.length+'/'+maxSlots}
function add(d){if(carried.length>=maxSlots){toast('BACK FULL',true);sound(130);return false}const m=itemMesh(d),e={id:uid++,d,m,mult:1,cooked:false,blessed:false};stackRoot.add(m);carried.push(e);layout();codex.add(d.id);save();lean=clamp(lean+d.weight*.72,0,35);sound(320+carried.length*28);vibrate(12);toast('+ '+d.name);if(mods.has('autoCook')&&tags(d,'food')){e.mult*=2;e.cooked=true;m.material.emissive.setHex(0x3a1c05);toast('AUTO-COOK ×2')}combos();maybeLevel();return true}
function removeAt(i){const e=carried.splice(i,1)[0];if(e)stackRoot.remove(e.m);layout();return e}
function combo(key,label){if(comboSeen.has(key))return false;comboSeen.add(key);toast(label);sound(523,.07,.035);setTimeout(()=>sound(659,.08,.025),60);vibrate(24);return true}
function combos(){for(let i=0;i<carried.length-1;i++){const a=carried[i],b=carried[i+1];if(tags(a.d,'fire')&&tags(b.d,'food')&&!b.cooked){b.cooked=true;b.mult*=3;b.m.material.emissive.setHex(0x4a2108);combo('cook'+b.id,'COOKED ×3')}if((a.d.id==='fish'&&b.d.id==='lantern')||(a.d.id==='lantern'&&b.d.id==='fish')){const f=a.d.id==='fish'?a:b;if(combo('king'+a.id+'-'+b.id,'GRILLED KING ×3')){f.mult*=3;f.m.scale.setScalar(1.18)}}if((a.d.id==='mirror'&&tags(b.d,'cursed'))||(b.d.id==='mirror'&&tags(a.d,'cursed'))){const c=a.d.id==='mirror'?b:a;if(!c.blessed){c.blessed=true;c.mult*=1.5;c.m.material.emissive.setHex(0x0c3440);lean=Math.max(0,lean-5);combo('bless'+c.id,'CURSE INVERTED')}}}
const ci=carried.findIndex(e=>e.d.id==='cheese'),ri=carried.findIndex(e=>tags(e.d,'critter'));if(ci>=0&&ri>=0&&ci!==ri&&combo('snack'+carried[ci].id+'-'+carried[ri].id,'SNACK TAX +12')){for(const i of[ci,ri].sort((a,b)=>b-a))removeAt(i);raidGold+=12}
if(carried[0]&&carried[0].d.id==='bomb'&&carried.some(e=>tags(e.d,'wood'))&&combo('char'+carried[0].id,'CHARCOAL — STABLE')){carried[0].mult*=1.6;lean=Math.max(0,lean-8)}
const crown=carried.find(e=>e.d.id==='crown');if(crown&&carried.filter(e=>tags(e.d,'metal')).length>=4&&combo('royal'+crown.id,'ROYAL TAX ×2'))crown.mult*=2;
const apple=carried.find(e=>e.d.id==='apple'),mirror=carried.find(e=>e.d.id==='mirror');if(apple&&mirror&&combo('oracle'+apple.id+'-'+mirror.id,'GOLDEN ORACLE ×2'))apple.mult*=2;
const gem=carried.find(e=>e.d.id==='gem'),idol=carried.find(e=>e.d.id==='idol');if(gem&&idol&&combo('night'+gem.id+'-'+idol.id,'NIGHT TITHE ×2')){gem.mult*=2;lean=Math.max(0,lean-4)}
if(carried[0]&&carried[0].d.id==='boots')combo('boots'+carried[0].id,'SPRING-LOCKED');if(carried[0]&&carried[0].d.id==='lead')combo('lead'+carried[0].id,'LEAD ANCHOR');const t=carried[carried.length-1];if(t&&t.d.id==='bell')combo('bell'+t.id,'LOUD TOP')}
const levels=[70,150,260,400,560,760];function maybeLevel(){if(nextLevel<levels.length&&value()>=levels[nextLevel]&&!paused){nextLevel++;setTimeout(showLevel,reduced?0:120)}}
function threeMods(){const p=[...MODS],o=[];while(o.length<3&&p.length)o.push(p.splice((Math.random()*p.length)|0,1)[0]);return o}
function renderChoices(){const root=el('modChoices');root.innerHTML='';for(const m of threeMods()){const b=document.createElement('button');b.className='choice';b.innerHTML='<b>'+m.title+'</b><span>'+m.desc+'</span>';b.onclick=()=>{mods.add(m.id);if(m.id==='slot')maxSlots++;if(m.id==='ghost')ghostUntil=performance.now()+20000;screens.level.classList.remove('active');paused=false;layout();toast(m.title)};root.appendChild(b)}}
function showLevel(){if(!running)return;paused=true;renderChoices();screens.level.classList.add('active');el('rerollBtn').classList.toggle('hidden',!meta.owned.shrine||rerolled)}el('rerollBtn').onclick=()=>{rerolled=true;renderChoices();el('rerollBtn').classList.add('hidden')};
function sellDistance(){let d=player.position.distanceTo(gate);for(const p of stalls)d=Math.min(d,player.position.distanceTo(p));return d}
function sell(exit=false){if(!running||!carried.length)return false;const top=carried[carried.length-1],range=top&&top.d.id==='bell'?6.2:3;if(sellDistance()>range){toast('FIND A SELL RING',true);return false}const n=value();raidGold+=n;let i=0;while(carried.length){stackRoot.remove(carried.pop().m);sound(360+(++i)*26,.035,.02)}lean=Math.max(0,lean-12);layout();toast('SLAM +'+n);vibrate(35);if(exit)endRaid('escaped');return true}
function drop(taxed=false){if(!running||!carried.length)return;const e=carried.pop();stackRoot.remove(e.m);layout();spawn(e.d,player.position.x+rnd(-1,1),player.position.z+rnd(-1,1),performance.now()+(taxed?1300:2500));lean=Math.max(0,lean-5);if(mods.has('dropGold')&&!taxed)raidGold+=6;toast(taxed?'GUARD TAX':'DE-GREED',taxed);sound(170)}
function pack(){const now=performance.now(),cd=mods.has('pack')?4000:8000;if(now<packReady){toast(Math.ceil((packReady-now)/1000)+'s',true);return}packReady=now+cd;lean=Math.max(0,lean-10);toast('PACKED');sound(250,.07,.03);vibrate(18)}
function avalanche(){slowUntil=performance.now()+300;toast('AVALANCHE!',true);vibrate([25,30,60]);sound(95,.18,.04);const exp=performance.now()+2500;while(carried.length){const e=carried.pop();stackRoot.remove(e.m);spawn(e.d,player.position.x+rnd(-2.4,2.4),player.position.z+rnd(-2.4,2.4),exp)}lean=8;layout()}
function startRaid(){Object.values(screens).forEach(s=>s.classList.remove('active'));hud.root.classList.remove('hidden');running=true;paused=false;raidTime=0;raidGold=0;lean=0;maxSlots=6+(meta.owned.hook?1:0);nextLevel=0;packReady=ghostUntil=guardCooldown=catReady=0;rerolled=false;mods.clear();comboSeen.clear();target=null;player.position.set(0,0,-1);fillBazaar();if(meta.owned.ledger)add(one(ITEMS.slice(0,5)));toast('WALK INTO LOOT')}
function endRaid(reason){if(!running)return;running=false;paused=false;hud.root.classList.add('hidden');const cut=reason==='escaped'?0:Math.floor(value()*.2),kept=raidGold+cut;bank+=kept;best=Math.max(best,kept);save();el('banked').textContent=kept;el('endEyebrow').textContent=reason==='escaped'?'PAYOUT GATE':'THE TOWER REMEMBERS';el('endTitle').textContent=reason==='escaped'?'GATE SLAM.':Math.max(1,Math.round(35-lean))+'° FROM GLORY';el('endCopy').textContent=reason==='escaped'?'You got out with '+kept+' gold.':'Dawn ate the rest. You kept '+kept+'.';screens.end.classList.add('active')}
function renderDen(){el('stash').textContent=bank;const g=el('upgradeGrid');g.innerHTML='';for(const u of UPGRADES){const owned=!!meta.owned[u.id],b=document.createElement('button');b.className='upgrade'+(owned?' owned':'');b.disabled=owned;b.innerHTML='<b>'+u.name+' — '+(owned?'OWNED':u.cost)+'</b><small>'+u.desc+'</small>';b.onclick=()=>{if(bank<u.cost){toast('NOT ENOUGH GOLD',true);return}bank-=u.cost;meta.owned[u.id]=true;save();renderDen();sound(480,.09,.03)};g.appendChild(b)}}
function showDen(){screens.end.classList.remove('active');screens.den.classList.add('active');renderDen()}
function updateGuards(dt,now){for(const q of guards){q.phase+=q.speed*dt*(meta.owned.disguise?.75:1);q.g.position.set(Math.cos(q.phase)*q.radius,0,Math.sin(q.phase)*q.radius);q.g.rotation.y=-q.phase;if(running&&now>ghostUntil&&now>guardCooldown&&player.position.distanceTo(q.g.position)<1.25&&carried.length){guardCooldown=now+2600;drop(true);if(carried.length)drop(true);toast('GUARD TAX: TOP 2',true)}}}
function cleanup(now){for(let i=loot.length-1;i>=0;i--)if(loot[i].expires&&now>loot[i].expires){lootRoot.remove(loot[i].m);loot.splice(i,1)}}
function touchLoot(){for(let i=loot.length-1;i>=0&&carried.length<maxSlots;i--)if(player.position.distanceTo(loot[i].m.position)<1.05){const w=loot.splice(i,1)[0];lootRoot.remove(w.m);add(w.d)}}
function cat(now){const top=carried[carried.length-1];if(!top||top.d.id!=='cat'||now<catReady)return;catReady=now+4500;let found=-1,dist=6.5;for(let i=0;i<loot.length;i++){const d=player.position.distanceTo(loot[i].m.position);if(d<dist){dist=d;found=i}}if(found>=0&&carried.length<maxSlots){const w=loot.splice(found,1)[0];lootRoot.remove(w.m);add(w.d);toast('CAT STOLE IT')}}
let lastYaw=0;function move(dt,now){const v=new THREE.Vector2((keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0));v.add(touch);if(target&&v.lengthSq()<.01){const dx=target.x-player.position.x,dz=target.z-player.position.z,d=Math.hypot(dx,dz);if(d>.35)v.set(dx/d,dz/d);else target=null}if(v.length()>1)v.normalize();const moving=v.lengthSq()>.01,lead=carried[0]&&carried[0].d.id==='lead',boots=carried[0]&&carried[0].d.id==='boots';const speed=5.2*(lead?.7:1);player.position.x+=v.x*speed*dt;player.position.z+=v.y*speed*dt;const rr=Math.hypot(player.position.x,player.position.z);if(rr>21.2){player.position.x*=21.2/rr;player.position.z*=21.2/rr}if(moving){const yaw=Math.atan2(v.x,v.y),turn=Math.abs(Math.atan2(Math.sin(yaw-lastYaw),Math.cos(yaw-lastYaw)));player.rotation.y=yaw;lastYaw=yaw;let gain=(.68+weight()*.07+turn*.4)*(mods.has('stable')?.75:1)*(lead?.2:1);if(boots)gain*=.22;lean+=gain*dt;touchLoot()}else lean-=dt*(meta.owned.moss?3.4:2.05);lean+=carried.filter(e=>tags(e.d,'cursed')&&!e.blessed).length*.045*dt;lean=clamp(lean,0,35);if(lean>=35)avalanche();const s=lean/35;stackRoot.rotation.z=Math.sin(now*.006)*s*.33;stackRoot.rotation.x=Math.cos(now*.0045)*s*.19;cat(now)}
const night=new THREE.Color(0x071014),dawn=new THREE.Color(0x193149),tmp=new THREE.Color();function sky(){const p=clamp((raidTime-240)/140,0,1);tmp.copy(night).lerp(dawn,p);scene.background.copy(tmp);scene.fog.color.copy(tmp)}
function cam(){const h=carried.length*.55,z=1+carried.length*.045,d=new THREE.Vector3(player.position.x+10*z,10.5+h*.5,player.position.z+11*z);camera.position.lerp(d,.08);camera.lookAt(player.position.x,1.3+h*.28,player.position.z)}
function drawHud(){hud.gold.textContent=raidGold;hud.value.textContent=value();hud.stack.textContent=carried.length+'/'+maxSlots;hud.best.textContent=best;const rem=Math.max(0,RAID+GRACE-raidTime),m=Math.floor(rem/60),s=Math.floor(rem%60);hud.time.textContent=m+':'+String(s).padStart(2,'0');hud.dawn.style.width=clamp(raidTime/RAID*100,0,100)+'%';hud.leanBar.style.width=(lean/35*100)+'%';hud.lean.textContent=lean.toFixed(0)+'°'}
let last=performance.now();function frame(now){requestAnimationFrame(frame);let dt=Math.min(.035,(now-last)/1000);last=now;if(now<slowUntil&&!reduced)dt*=.25;updateGuards(dt,now);cleanup(now);if(running&&!paused){raidTime+=dt;move(dt,now);sky();if(raidTime>=RAID&&player.position.distanceTo(gate)<2.9)sell(true);else if(raidTime>=RAID+GRACE)endRaid('dawn')}cam();drawHud();renderer.render(scene,camera)}requestAnimationFrame(frame);
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(k==='q')drop();if(k===' '){e.preventDefault();pack()}if(k==='e')sell(false)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const ray=new THREE.Raycaster(),pt=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||!running)return;pt.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pt,camera);if(ray.ray.intersectPlane(plane,hit))target=hit.clone()});
const stick=el('stick'),knob=el('knob');let sid=null;function stickMove(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let dx=e.clientX-cx,dy=e.clientY-cy,len=Math.hypot(dx,dy)||1,k=Math.min(1,max/len);dx*=k;dy*=k;knob.style.transform='translate('+dx+'px,'+dy+'px)';touch.set(dx/max,dy/max)}stick.addEventListener('pointerdown',e=>{sid=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===sid)stickMove(e)});function stickEnd(e){if(e.pointerId!==sid)return;sid=null;touch.set(0,0);knob.style.transform='translate(0,0)'}stick.addEventListener('pointerup',stickEnd);stick.addEventListener('pointercancel',stickEnd);
el('dropBtn').onclick=()=>drop();el('packBtn').onclick=pack;el('sellBtn').onclick=()=>sell(false);el('startBtn').onclick=startRaid;el('againBtn').onclick=startRaid;el('denBtn').onclick=showDen;el('denRaidBtn').onclick=startRaid;renderDen();drawHud();
